# Generated by Django 3.2.3 on 2021-06-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_title', models.CharField(max_length=100)),
                ('Album_format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_title', models.CharField(max_length=100)),
                ('Song_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.album')),
            ],
        ),
    ]
